### ISSUE TITLE
[contracts] typescript lint error Web3Provider type not assignable

### ISSUE THREAD

**Issue by AlexXiong97** [counterfactual/monorepo#1058]
File: [`packages/contracts/test/static-call.spec.ts`](https://github.com/counterfactual/monorepo/blob/master/packages/contracts/test/static-call.spec.ts):

Here's a weird error message from my editor:
> Type 'import(".../counterfactual/monorepo/node_modules/ethereum-waffle/node_modules/ethers/providers/web3-provider").Web3Provider' is not assignable to type 'import(".../counterfactual/monorepo/node_modules/ethers/providers/web3-provider").Web3Provider'.  Types have separate declarations of a private property '_sendAsync'.

Here's the screenshot:
![Screenshot from 2019-03-15 16-49-26](https://user-images.githubusercontent.com/20514086/54434310-e7a48300-4768-11e9-960e-3ce03827f7d2.png)

Confirmed with @snario with the error, but as all tests pass, nothing serious was affected, left this issue for future investigation.

**Comment by snario** [comment]
Seems that `ethereum-waffle` dependencies is fetching a different version of `ethers` than `@counterfactual/contracts`

**Comment by AlexXiong97** [comment]
Good catch, `ethereum-waffle` uses `4.0.0` and `ethers` currently is `4.0.27`. 
After a bit of investigation, here's the differences made in `Web3Provider` type (which extends `JsonRpcProvider` type):

in [`4.0.0`](https://github.com/ethers-io/ethers.js/blob/061b0eae1d4c570aedd9bee1971afa43fcdae1a6/providers/json-rpc-provider.d.ts#L30)
in [`4.0.27`](https://github.com/ethers-io/ethers.js/blob/master/providers/json-rpc-provider.d.ts#L31)

**Comment by snario** [comment]
@marekkirejczyk can we make it a `peerDependency`?

@AlexXiong97 maybe we can use the module resolutions config in `package.json`

**Comment by sz-piotr** [comment]
Hey. I have done some investigating on the issue and have not found the problems you describe. Waffle specifies that it depends on `"ethers": "^4.0.0"` which means that installing it will default to the latest version compatible with ethers 4, which is `4.0.27`. Tools like npm and yarn understand and respect this setting.

I couldn't reproduce the issue on a clean version of this repository:

1. Clone the monorepo repository
2. Run `yarn && yarn build && yarn test` and see them all succeed without errors
3. Check the installed packages
```
$ yarn why ethers
yarn why v1.13.0
[1/4] 🤔  Why do we have the module "ethers"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ethers@4.0.27"
info Reasons this module exists
   - "_project_#web3-eth-abi" depends on it
   - Hoisted from "_project_#web3-eth-abi#ethers"
   - Hoisted from "_project_#@counterfactual#apps#ethers"
   - Hoisted from "_project_#@counterfactual#node#ethers"
   - Hoisted from "_project_#@counterfactual#typescript-typings#ethers"
   - Hoisted from "_project_#@counterfactual#tic-tac-toe-bot#ethers"
   - Hoisted from "_project_#@counterfactual#types#ethers"
   - Hoisted from "_project_#@counterfactual#contracts#ethers"
   - Hoisted from "_project_#@counterfactual#cf.js#ethers"
   - Hoisted from "_project_#@counterfactual#high-roller-bot#ethers"
   - Hoisted from "_project_#@counterfactual#machine#ethers"
   - Hoisted from "_project_#@counterfactual#contracts#ethereum-waffle#ethers"
   - Hoisted from "_project_#@counterfactual#typescript-typings#truffle-contract#ethers"
   - Hoisted from "_project_#@counterfactual#contracts#zos-lib#ethers"
info Disk size without dependencies: "4.2MB"
info Disk size with unique dependencies: "8.17MB"
info Disk size with transitive dependencies: "8.31MB"
info Number of shared dependencies: 13
✨  Done in 1.31s.
```
```
$ yarn why ethereum-waffle
yarn why v1.13.0
[1/4] 🤔  Why do we have the module "ethereum-waffle"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ethereum-waffle@2.0.7"
info Reasons this module exists
   - "_project_#@counterfactual#contracts" depends on it
   - Hoisted from "_project_#@counterfactual#contracts#ethereum-waffle"
   - Hoisted from "_project_#@counterfactual#typescript-typings#ethereum-waffle"
   - Hoisted from "_project_#@counterfactual#apps#ethereum-waffle"
   - Hoisted from "_project_#@counterfactual#machine#ethereum-waffle"
info Disk size without dependencies: "136.07MB"
info Disk size with unique dependencies: "170.26MB"
info Disk size with transitive dependencies: "250.82MB"
info Number of shared dependencies: 236
✨  Done in 2.25s.
```
4. Open `packages/contracts/test/static-call.spec.ts` in vs code and see no errors

**Comment by AlexXiong97** [comment]
@sz-piotr Thanks for the feedback, I've double checked (clean clone and build and open vscode), the error still comes out, are you sure you checkout to the pre-fix version of the file? i.e. `cb14a3b7e` (my guess is that when you clone this repo, the yarn package resolution is already merged in, thus no error show up)

> Waffle specifies that it depends on "ethers": "^4.0.0" which means that installing it will default to the latest version compatible with ethers 4, which is 4.0.27. Tools like npm and yarn understand and respect this setting.

I agree with ^^ that, but I'm not sure yarn or npm will check for declared types in the file, from yarn's point of view, the minor bump/patch to 4.0.27 is indeed compatible, but typescript linter will shout out error?
