### ISSUE TITLE
[playground] Investigate issue that causes some users to end up in un-collateralized state with hub

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1152]
In some cases the following will happen:

1. User creates a new account
2. Hub creates the multisig wallet (creates the state channel)
3. User successfully deposits
4. Hub installs balance refund, deposits, but uninstallation of balance refund fails

The user ends up in a bizarre state where the UI progresses but the hub deposit does not finalize. Worse still, the user cannot trigger a new deposit because "a deposit is already occurring in the channel".

**Comment by joelalejandro** [comment]
This is no longer ocurring. Closing.
