### ISSUE TITLE
[specs, machine] Installing/Uninstalling more than one app is insecure

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1160]
The Update, Install, Setup, and Uninstall protocols use a MultiSend commitment. The goal of this was to make the protocol "one round trip" however this is longer a goal. Furthermore, because updates to the free balance do not commute, this makes installing/uninstalling more than one app unsecure.

**Comment by cf19drofxots** [comment]
Out of curiosity, what are the tradeoffs being made here? What's the advantage of unrolling?

**Comment by snario** [comment]
They areBasically when they are rolled up two parties A and B only need to do one round trip to execute a protocol. A signs and sends to B, B countersigns and sends to A, done. The problem is that you are signing a transaction which does multiple things in one go, not all of which will strictly need to be executed on chain in one go.

When they are not rolled up, you end up with multiple commitments which can be put on-chain piecemeal but the tradeoff is that the protocol becomes multiple round trips. A to B, B to A, A back to B, B back to A, done, for example.

We have decided the one-round trip goal is not that advantageous / worth it for the trouble this causes handling on chain challenges.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
fixed by #1774
