### ISSUE TITLE
[playground-server][node] Counter depositing occasionally does not happen

### ISSUE THREAD

**Issue by cf19drofxots** [counterfactual/monorepo#1174]
After a multisig is deployed and a user deposits, some times the counter depositing from the playground server does not happen.

This needs to be reproduced again to dump logs here.

**Comment by cf19drofxots** [comment]
Haven't been able to repro this yet reliably so moving out of in-progress for now.

**Comment by joelalejandro** [comment]
Closing, we've learned that this usually happens when there's a version discrepancy between the Node instances.
