### ISSUE TITLE
[docs] Do a better job communicating to others how to run the Playground locally

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1188]
Several people have tried to run the Playground and had errors. The common ones are:

- Not building the entire monorepo after checkout (i.e., running `yarn build`)
- Trying to run `yarn start` in the `playground` package instead of `yarn run:playground` in the monorepo root)
- Not funding the hub accounts as needed or described in a README
- Not knowing about the `playground:matchmakeWith` dev flag
- Not knowing how to start the bots or that we have bots at all

**Comment by snario** [comment]
Does #1220 cover all of this issue @joelalejandro? If so we can close it

**Comment by joelalejandro** [comment]
Yes, it does. I'm closing this.
