### ISSUE TITLE
Create a `counterfactual-app` Truffle box 

### ISSUE THREAD

**Issue by ebryn** [counterfactual/monorepo#1207]
This will provide a super basic project structure uncoupled from any kind of build tooling.

Truffle documentation on how to create a box: https://truffleframework.com/docs/truffle/advanced/creating-a-truffle-box
Example box we can use to base our work off: https://github.com/truffle-box/pet-shop-box

New users should be able to essentially do:

```
mkdir my-app
truffle unbox counterfactual-app
ganache-cli &
truffle compile
truffle migrate
npm run dev
```

and boom. They have a Layer 2 State Channels dapp up and running with nearly no configuration.

I expect the project structure to look something like:
```
app/app.js
app/app.css
app/index.html
contracts/app.sol
```

This will be used by our Getting Start Guide project and be a foundational part of our future documentation/guides.

`app.sol` will have a boilerplate CounterfactualApp implementation, similar to:
```solidity
pragma solidity 0.5.3;
pragma experimental "ABIEncoderV2";

import "@counterfactual/contracts/contracts/libs/Transfer.sol";
import "@counterfactual/contracts/contracts/CounterfactualApp.sol";


contract HighRollerApp is CounterfactualApp {
  function isStateTerminal(bytes memory encodedState)
    public
    pure
    returns (bool)
  {
    return false;
  }

  function getTurnTaker(bytes memory encodedState, address[] memory signingKeys)
    public
    pure
    returns (address)
  {
    return 0x72bA7d8E73Fe8Eb666Ea66babC8116a41bFb10e2;
  }

  function applyAction(bytes memory encodedState, bytes memory encodedAction)
    public
    pure
    returns (bytes memory)
  {
    return abi.encode();
  }

  function resolve(bytes memory encodedState, Transfer.Terms memory terms)
    public
    pure
    returns (Transfer.Transaction memory)
  {
    return Transfer.Transaction(
      terms.assetType,
      terms.token,
      new address[](2),
      new uint256[](2),
      new bytes[](2)
    );
  }

}
```

**Comment by snario** [comment]
This is done, right? @patience-tema-baron @ebryn Can we close it?

**Comment by ebryn** [comment]
Yep!
