### ISSUE TITLE
[contracts] Update waffle.json with a waffle.js script

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1211]
It seems possible to replace `waffle.json` with a `waffle.js` script.

We should do this and configure the script to do the following:

- Check if the environment is CI and is so, use `native` for `solc` cc @AlexXiong97
- Check the value of the `solc` package inside `node_modules` and if it is the expected version (i.e., 0.5.7 atm) then use that, else specify `solcVersion` and fetch it remotely

For the second bullet point, it might make sense to instead use some kind of Node module resolution to guarantee `solc` is the same version regardless of other modules depdendency requirements too.... to be investigated.

**Comment by snario** [comment]
Might be useful to do for / in addition to work on #1204 as that is what identified this issue

**Comment by AlexXiong97** [comment]
fixed in #1204. is it still under review/qa or shall we close this issue now?
