### ISSUE TITLE
Transfers are forced to use the same token for all beneficiaries

### ISSUE THREAD

**Issue by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [counterfactual/monorepo#1222]
The current `Transfer` struct doesn't support different tokens to different beneficiaries.

**Comment by snario** [comment]
This effects #1157

**Comment by AlexXiong97** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll but should be a relatively straightforward fix right?
https://github.com/counterfactual/monorepo/blob/master/packages/contracts/contracts/libs/Transfer.sol#L27
change from `uint8` to `uint8[]` and modify other files dependent/affected on this.

I could help with this one, any other better alternatives in mind?
