### ISSUE TITLE
Machine imports generated artifacts

### ISSUE THREAD

**Issue by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [counterfactual/monorepo#1224]
The machine `import`s JSON files directly from the `@counterfactual/contracts/build` directory. These files are generated by the build process of the contracts. This means that `tsc` in the machine fails if `yarn build` from the contracts have never been run, and that the typescript language server also reports (correctly) the imports as incorrect

**Comment by snario** [comment]
This is the expected behaviour at the moment. One improvement we can do is in conjunction with #692 have `@counterfactual/contracts` export a JS object which contains the built artifacts and package that up essentially instead of using the `files` feature of npm `package.json`s.

**Comment by snario** [comment]
The other alternative is to add build artifacts into the source code; but I don't personally think we should do that.

**Comment by snario** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll thoughts? Will close this if none.
