### ISSUE TITLE
[cf.js] AppInstance takeAction returns incorrect response

### ISSUE THREAD

**Issue by Alonski** [counterfactual/monorepo#1247]
# Bug Report

There is an issue with `takeAction` where it sometimes doesn't contain a result as part of the response from `this.provider.callRawNodeMethod(Node.MethodName.TAKE_ACTION...`
The function in question: https://github.com/counterfactual/monorepo/blob/master/packages/cf.js/src/app-instance.ts#L87

## Data sent:
`action`:
```javascript
action: {
actionHash: "0xdfdaa4d168f0be935a1e1d12b555995bc5ea67bd33fce1bc5be0a1e0a381fc90"
actionType: 3
number: "2"
}
```

## Expected
I expect the response to look like:
```javascript
response: {
requestId: "1554735376806"
result:
newState:
commitHash: "0x0000000000000000000000000000000000000000000000000000000000000000"
playerAddrs: (2) ["0x51C8cD1752085447F5A44260415D153A3cA087d0", "0x8563e5B8017D449A3CdA9513545C18D02a731E5B"]
playerFirstNumber: {_hex: "0x00"}
playerSecondNumber: {_hex: "0x00"}
salt: "0x0000000000000000000000000000000000000000000000000000000000000000"
stage: 1
type: "takeAction"
}
```

## Received (Sometimes)
The broken response looks like:
```javascript
response: {type: "takeAction", requestId: "1554735296502"}
```

## To Reproduce
Currently this is happening in the Metamask integration branches. I am playing a game of High Roller. After clicking `Roll your dice` Button the `takeAction` function is entered 5 times in `cf.js` on the client. On the 3rd and 5th time that the function is called `response.result` is undefined.

## Image
![image](https://user-images.githubusercontent.com/452199/55733536-aa10de00-5a26-11e9-9981-076f41d4ff2d.png)

**Comment by snario** [comment]
@Alonski is this still an issue? Seems like a bug with the provider you are using?

**Comment by Alonski** [comment]
@snario I managed to work around this issue. I am still not sure why it was happening. We can close this since it was only happening to me but should probably remember that its a thing if it happens in the future.
