### ISSUE TITLE
[playground] Use deposit UI similar to onboarding

### ISSUE THREAD

**Issue by Alonski** [counterfactual/monorepo#1249]
Currently during Account Registration and initial deposit into the multisig we show a different UI that indicates that the deposit is in progress, and we disable the deposit button.

On the `exchange` screen we don't have this UI. We should add this so that users don't get confused and don't click the deposit button multiple times.

**Comment by snario** [comment]
I think as the Playground is moved to the MetaMask UI that we may not need to worry about this? @ebryn what do you think makes sense?

**Comment by joelalejandro** [comment]
This has been covered by #1953.
