### ISSUE TITLE
Routing of machine protocol messages uses params

### ISSUE THREAD

**Issue by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [counterfactual/monorepo#1252]
The key computation at https://github.com/counterfactual/monorepo/blob/0542bbc3856fd533d09658a3089e5a7abaafc843/packages/node/src/node.ts#L194 uses the `params` field of messages. However the fact that all messages include `params` is a historical accident (only some of them need to) that should be fixed. However the routing mechanism prevents this from being fixed.

**Comment by snario** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll can you please add detail?

**Comment by snario** [comment]
Solution is to generate a UUID and use it in-place of this technique. Presently we just encode the object of the entire message basically as a means of guaranteeing uniqueness of the message. Let's use UUID.
