### ISSUE TITLE
Remove terms.limit from example contracts

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1256]
We plan on removing this notion in the future, so let's deprecate its usage now.

**Comment by AlexXiong97** [comment]
Question: does this mean `Terms` type will be deprecated? I remember @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll once explained to me that the purpose of this is just an extra layer of protecting users from accidentally signing excessive amount?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
> Or will this limit check be done in the new interpreter?

Yeah, the proposed interpreter design under construction/evaluation does this.

As a general principle it was weird that `Terms` was used both as a static guarantee, and as an app-definition-interpreted parameter to an app instance.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
closing in favour of #1257
