### ISSUE TITLE
[epic] Better support for different asset classes

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1257]
The current design requires our code to explicitly enumerate all resolution type. Currently it the enumerated list is `ETH`, `ERC20` and `to/value/data`. The last is used as a "catch-all" since it could technically be used to implement the other two. The reason that things don't all use `to/value/data` is for safety and static guarantees. However, to implement different asset types safely requires extending the enumerated list.

# Current Positions

### How does a CounterfactualApp know _how much_ to send to each person?
It is based on the **state** of the app.

### How does a CounterfactualApp know _who_ to send to? Does it need to?
An interpretter is introduced which pre-commits to how a resolution of an application might be distributed.

### What "limits" what a CounterfactualApp can do? (e.g., total ETH)
An interpretter also defines a `limit()` functions.

# Requirements

- A developer of an asset should be able to write a plugin / handler for their asset that all existing CounterfactualApps might be able to use in the resolution of their app code

- The same on-chain deployed CounterfactualApp contract should work for ETH, ERC20, and new asset types defined after the contract has been deployed

- A faulty CounterfactualApp must not be able to lose more than the maximum amount allocated to it as defined by some kind of asset interpreter / pre-commitment by the channel users

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
Additional requirement: support coinshuffle-outcome type resolve outcomes
