### ISSUE TITLE
[repo] Add a CI check to ensure yarn.lock is up-to-date

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#1260]
Surfaced from discussion on https://github.com/counterfactual/monorepo/pull/1217.

**Comment by AlexXiong97** [comment]
Thanks to @Alonski 's [recommendation](https://github.com/counterfactual/monorepo/pull/1217#issuecomment-481529310), I also vote for using [renovate ](https://renovatebot.com/)over greenkeeper to automate the process.

allowing greenkeeper to update in CI is a bit complicated and confusing. [see here](https://github.com/greenkeeperio/greenkeeper-lockfile#circleci-workflows)

**Comment by snario** [comment]
See #1261 which needs to be worked on.

We can remove Greenkeeper in that PR, too.

**Comment by snario** [comment]
Docs: https://renovatebot.com/docs/configuration-options/

**Comment by AlexXiong97** [comment]
I have deleted the `greenkeeper.json` in a further commit in #1261, but to fully disable greenkeeper, we need to delete from Github setting Github App section. 

Other configuration should be proposed in another issue with the exact requirements specified?

**Comment by snario** [comment]
@AlexXiong97 I think we need to also blacklist all the @counterfactual packages as we had done on greenkeeper.json

**Comment by snario** [comment]
I'll remove greenkeeper

**Comment by AlexXiong97** [comment]
@snario may I ask why ignoring all @counterfactual packages? Their version will only be updated if published, right? (plus, I don't know where in the pipeline will the team publish/update the npm package, is it somewhere in the CD process?)

If we choose not to ignore them, will it break anything?

And also what about @stencil and Jest?

**Comment by snario** [comment]
At the moment we require that we as developers bump the versions in our PRs for CF packages.

For Stencil and Jest we also need to blacklist them because `react-scripts` / create-react-app sets them to specific versions it requires.

**Comment by AlexXiong97** [comment]
understood, I have added the same blacklist in the `renovate.json`.

**Comment by snario** [comment]
#1261 should close this issue
