### ISSUE TITLE
[playground] Playground tests sometimes hang

### ISSUE THREAD

**Issue by cf19drofxots** [counterfactual/monorepo#1401]
Seems like some time the playground tests all run but then don't quite finish so the CI job never terminates.

<img width="1402" alt="Screen Shot 2019-05-02 at 6 20 18 PM" src="https://user-images.githubusercontent.com/38441757/57115995-14a3f980-6d07-11e9-9e8b-466ebe30124f.png">

As can be seen in the top right corner, this run was still "running" after 6 minutes.

cc @joelalejandro

**Comment by cf19drofxots** [comment]
This is quite annoying so tackling this atm.

**Comment by cf19drofxots** [comment]
Put this on pause as of https://github.com/counterfactual/monorepo/pull/1426

**Comment by joelalejandro** [comment]
This is no longer necessary, as part of #2033.
