### ISSUE TITLE
Node has 2 different methods of running integration tests

### ISSUE THREAD

**Issue by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [counterfactual/monorepo#1420]
1. Using `test.sh`
2. Using `global-setup.jest.ts`

**Comment by snario** [comment]
@cf19drofxots what do you think we should do in terms of "correct" path to proceed? Both are basically just setup scripts to start `ganache-cli` I think.

The jest setup file seems more flexible for future use cases. Delete `test.sh`?

**Comment by cf19drofxots** [comment]
Most likely delete `test.sh` - I'll take this and consolidate these two methods
