### ISSUE TITLE
[node] [cf.js] Implement JSON-RPC protocol 

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#1614]
## Motivation

Standardization efforts with wallet vendors have led us to realize that using JSON:API Operations as described in #1242 was not the best course of action we could take.

In the Ethereum community, the [JSON-RPC](https://www.jsonrpc.org/specification) protocol is well established and has enough similarity with our current data structures (i.e. [`NodeMessage`](https://github.com/counterfactual/monorepo/blob/0d05d27ff04fb5757b3db5765f86cc9621f52b53/packages/node/src/types.ts#L7-L10) and [its extensions](https://github.com/counterfactual/monorepo/blob/0d05d27ff04fb5757b3db5765f86cc9621f52b53/packages/node/src/types.ts#L38-L43)).

## Work to do

Using a minimal [RPC server library](https://github.com/prototypal/rpc-server) as support, the idea is to implement a full version of what started in #1613 as a spike:

- [x] Extend the `NodeController` to inherit from `rpc-server`'s `Controller` class, to enable JSONRPC annotations (✔️ via 28389bb)
- [x] Annotate each Node method with the `@jsonRpcMethod` decorator (as seen [here](https://github.com/counterfactual/monorepo/pull/1613/files#diff-2f0eb6c5a8b9282c13ce0432d44d30eaR50)) 
    - [x] Required by CF.js
      - [x] `proposeInstall` (✔️ via 2dcbdef)
      - [x] `proposeInstallVirtual` (✔️ via 467cede)
      - [x] `getState` (✔️ via 1adcb07)
      - [x] `takeAction` (✔️ via 6cbe73a)
      - [x] `uninstall` (✔️ via 0fafe3e5)
      - [x] `getAppInstances` (✔️ via f80c4090)
      - [x] `install` (✔️ via 540af214)
      - [x] `installVirtual` (✔️ via 0a29264)
      - [x] `rejectInstall` (✔️ via 511214f6)
      - [x] `getAppInstance` (✔️ via c485fb8b)
    - [x] Required by the Playground UI / soon-to-be CF Wallet
      - [x] `getFreeBalanceState` (✔️ via ff961523)
      - [x] `deposit` (✔️ via 714a5a80)
      - [x] `withdraw` (✔️ via 54613f7e)
    - [x] Required by the Playground Server
      - [x] `createChannel` (✔️ via bf84619)
- [x] Install and bundle `prototypal/rpc-server` in CF.js to format JSON-RPC messages (✔️ via 3386ef21)
- [x] Have the Node encode RPC responses as JSON-RPC
  - [x] Create new class `NodeRouter` extending from `rpc-server`'s `Router` (✔️ via 7dff3dce)
  - [x] Add response encoding (✔️ via 258d8a5c)
- [x] Connect RPC router to Node event system (✔️ via 64a6e31e)
- [x] Serialize/deserialize event payloads (NodeMessage <-> JSON-RPC) (✔️ via 8f56c391)
- [x] Port messaging methods in `CF.Provider` to handle JSON-RPC
  - [x] `callRawNodeMethod` (✔️ via 0cd93606 & 84f3be48)
  - [x] `handleNodeError` (✔️ via 4673ce68 & 84f3be48)
  - [x] `handleNodeMethodResponse` (✔️ via ffb12ccf & 84f3be48)
  - [x] `onNodeMessage` (✔️ via 84f3be48)
- [x] Update Playground UI interactions with the Node to use JSON-RPC
  - [x] Node type interface for Stencil (✔️ via 1f325e6)
  - [x] `AppRoot` 
    - [x] Call to `getBalances` (✔️ via dfd4ceaa)
    - [x] Call to `deposit` (✔️ via e110fbc0)
    - [x] Call to `withdraw` (✔️ via 3f9c5ea2)
- [x] Update Playground Server interactions with the Node to use JSON-RPC
  - [x] `Node`
    - [x] Call to `createChannel` - user's multisig (✔️ via bf84619)
    - [x] Call to `deposit` - channel collateralization (✔️ via 4e132010)
- [x] Make all CF.js tests pass with the new format (✔️ via 808e9c53)
- [x] Make al Node tests pass with the new format (✔️ via 5bf102d)
- [x] Make all CF.wallet tests pass with the new format (✔️ via 12bf79f)

💬 JSONRPC methods are being named following the `chan_${methodName}` format for starters, but we can change that at any time. **Feel free to propose better names!**

## Format for new messages

All messages should conform to the following payload, using the _named parameters_ version:

```json
{
  "jsonrpc": "2.0",
  "method": "method_name",
  "params": {
    "key": "value"
  },
  "id": 1234
}
```
> 🔔 JSONRPC works with numeric identifiers, so we won't be able to use an hexadecimal representation of UUIDs anymore.

## Status updates

6/12
- Implementation finished!
- Finished refactoring the Node tests as of 5bf102d.

6/7
- Began refactoring the Node tests as of d9337fdb.

6/6:
- Tests are passing in CF.js as of 808e9c53!

6/4:
- It's possible to test these changes by checking out commit d8eda85. It allows a user to register in the Playground. `chan_create` call works OK. Deposits can't be adequately handled due to event handling not being available as of this commit.
- Playground-Node interactions will be handled by CFWallet, so some of these changes will be finished after merging #1608.

**Comment by ArjunBhuptani** [comment]
Can this be synced up against: https://paper.dropbox.com/doc/v2-Networking-Specification--AeUJX_4GWvHm4J5d6POlr~_XAg-CNaIt9yWfFMh56Er90vjN ?

@snario

**Comment by ebryn** [comment]
@ArjunBhuptani we're going to look at that as a separate refactoring step

**Comment by ArjunBhuptani** [comment]
What do you mean?

Our provider spec is just a rough doc put together from my conversations with Liam. It makes sense to have a standard between us ASAP (especially so that wallets don't implement the wrong methods)

**Comment by ArjunBhuptani** [comment]
FYI: [This](https://paper.dropbox.com/doc/v2.0-Client-API--AehHumRvKnxfA1mO~8K9fSaNAg-huohiooFiziOopxe5OkaJ) is what we have for our v2.0 API.

To allow for a CF-enabled app to talk to a Connext wallet or vice versa, the Connext client will need to expose low level fns which map to CF's `proposeInstall` `install` etc. via JSON RPC
