### ISSUE TITLE
[node] ETH transfer outcome assumes only 1 transfer

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#1643]
Our app resolves to two transfers. This throws the following error when trying to uninstall:
```
(node:79165) UnhandledPromiseRejectionWarning: Error: Outcome function returned unexpected shape
    at computeEthTransferIncrement (/Users/rahul/Desktop/connext/connext/monorepo/packages/node/src/protocol/utils/get-outcome-increments.ts:20:11)
    at computeFreeBalanceIncrements (/Users/rahul/Desktop/connext/connext/monorepo/packages/node/src/protocol/utils/get-outcome-increments.ts:62:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is caused by the following code here, which appears to assume all decoded transfer arrays are `length === 1`:
```
function computeEthTransferIncrement(outcome): [string, BigNumber] {
  const decoded = defaultAbiCoder.decode(["tuple(address,uint256)[]"], outcome);

  if (
    !(
      decoded.length === 1 &&
      decoded[0].length === 1 &&
      decoded[0][0].length === 2
    )
  ) {
    throw new Error("Outcome function returned unexpected shape");
  }
  const [[[address, to]]] = decoded;

  return [address, to];
}
```

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
Ah, I remember the cause of this. I built this section of the code to resemble the old (restricted to two-party) as much as possible. Sorry!

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
@rhlsthrm I am working on fixing this, but can you point to a failing test case so that I can test my fix?

**Comment by rhlsthrm** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll this is the test I used to determine the failure: https://github.com/counterfactual/monorepo/blob/master/packages/apps/test/eth-transfer-app.spec.ts#L126. You might need to change the test code if you change the protocol itself.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
that test is successful - can you give a branch with a test that *fails* with the same error that you have in the initial report?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
@rhlsthrm I fixed the offending lines in https://github.com/counterfactual/monorepo/pull/1673
