### ISSUE TITLE
[contracts, node] Build artifacts output directory changed, node does not account for it

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#1917]
In the latest released NPM version of `@counterfactual/contracts` v0.1.8, the build artifacts output directory changed. The artifacts are now in `node_modules/@counterfactual/contracts/build` as opposed to `node_modules/@counterfactual/contracts/build/contracts`.

The node code does not account for this change ([example here](https://github.com/counterfactual/monorepo/blob/master/packages/node/src/ethereum/setup-commitment.ts#L1)). This causes errors during create channel and surely subsequent operations.

**Comment by cf19drofxots** [comment]
This is fixed in the referenced PR.
