### ISSUE TITLE
[wallet-ui] Support different asset types on the Exchange and the Onboarding Deposit

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#1955]
Once #1953 is resolved, we're gonna iterate to support selecting what kind of asset the user is depositing or withdrawing.

This also affects the Deposit screen for the onboarding flow, previously developed in #1732.

**Comment by spersico** [comment]
@snario Do you know where we can get the list of types of assets?

**Comment by snario** [comment]
ETH and ERC20 tokens for now
