### ISSUE TITLE
[node] Withdrawal sending to incorrect recipient with 0 value tx

### ISSUE THREAD

**Issue by LayneHaber** [counterfactual/monorepo#1962]
There are a couple of bugs around submitting a withdrawal. When no recipient is supplied, the rpc method returns the correct recipient in the response:
```
Withdraw Response: {
  "recipient": "0x7D745b331737765515749D5724b220C0Ac4cFA2A",
  "txHash": "0x6c1298547c6a8cae1596416de00c1351b656d716fc33da64840f6cfcb7e2c40b"
}
```
But the [transaction submitted](https://kovan.etherscan.io/tx/0x6c1298547c6a8cae1596416de00c1351b656d716fc33da64840f6cfcb7e2c40b) is to a different account and has 0 value. This one should have been to the listed recipient in the response, and have a value of 0.09 ETH.

When a recipient is supplied, the same issues apply (i.e transaction is going to a separate recipient and has no value):
```
Withdraw Response: {
  "recipient": "0xaDcf80839987fABD4BEEacbe7eD93Fff5D3a0761",
  "txHash": "0x784e3fa4a340533aa873be29c82d84354202b740e7b2ebf27333ce71afd74ed5"
}
```

[Transaction record](https://kovan.etherscan.io/tx/0x784e3fa4a340533aa873be29c82d84354202b740e7b2ebf27333ce71afd74ed5), should have 0.01 ETH.

**Comment by cf19drofxots** [comment]
@LayneHaber were you able to repro this either in the CF test context or within indra?

**Comment by cf19drofxots** [comment]
Closing this for the same reason as the linked PR was closed
