### ISSUE TITLE
[wallet-ui] [metamask] Wrong balance is being shown on the user infobox

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#1992]
Apparently the Metamask controller for `request:user` has a `0.2` hardcoded: 

https://github.com/prototypal/metamask-extension/blob/9acaf3fd89acd6dd73c840c50bc524b1672594aa/app/scripts/plugins/counterfactual.js#L242-L248

**Comment by Alonski** [comment]
The API that retrieves user info. `api/user/me` does not return a balance for the user.

The solution here is to remove the balance returned from `request:user` and instead add a `request:balances` in the WalletUI to get the balance for the user.

**Comment by joelalejandro** [comment]
Closed via #2067.
