### ISSUE TITLE
[node] Show zero free balance instead of error for token without free balance

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2016]
Right now, we get an error when we query free balance for a token that does not have any: `Error: No free balance exists for the specified token: 0xdDA6327139485221633A1FcD65f4aC932E60A2e1`

Instead of an error that we have to catch on the caller side, it would be more beneficial to display a zero balance. What do you think?

**Comment by joelalejandro** [comment]
@spersico This might be related to what we experienced today.

**Comment by joelalejandro** [comment]
@rhlsthrm I agree it's something we should consider. Althought it might be more accurate to reflect that the token does not have a free balance contract deployed, it adds complexity and nuances that could be easily handled by the Node.

**Comment by cf19drofxots** [comment]
Returning a zero balance seems fine. I'll modify the API.
