### ISSUE TITLE
[node] ERC20 transfers always transferring ETH

### ISSUE THREAD

**Issue by LayneHaber** [counterfactual/monorepo#2064]
alright more thorough testing on the transfer issues with node version `0.2.32`:
1. ETH transfers with no ETH collateral in senders channel and no deposit for receiver in receiver channel, but properly collateralized with ETH :white_check_mark: 
2. ERC20 transfers with no collateral in senders channel and no deposit for receiver in receiver channel, but properly collateralised with ERC20 :no_entry_sign: . `error: underflow in merge` on receiver bot
3. ERC20 transfers with no collateral in senders channel and no deposit for receiver in receiver channel, collateralized with ETH and ERC20 :no_entry_sign: . `error: underflow in merge` on hub
4. ERC20 transfers with ETH and ERC20 on senders side, and no deposit for receiver in receiver channel, collateralized with ETH and ERC20 :neutral_face: . doesnt throw error, but only transfers ETH

my guess is its all connected to the same issue, (4) only doesnt throw because its actually operating in ETH and (2) and (3) are throwing underflows because someone in the virtual app chain is missing eth in their balance (sender for (3) and recipient for (2))

**Comment by rhlsthrm** [comment]
I think this can be closed now @LayneHaber

**Comment by cf19drofxots** [comment]
Closing. @LayneHaber re-open if necessary.
