### ISSUE TITLE
[monorepo] Cache files based on package.json not on yarn.lock 

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#208]
The CI breaks when yarn.lock is computed using a different version of `yarn` from `1.10.1`. I think a fix to this should be to change `circle.yaml` to cache based on the various `package.json` files instead of caching based on the `yarn.lock` file.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
why would an out-of-sync node_modules cause the build to fail?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
FYI: the recommended thing to cache is the yarn cache directory, not the `node_modules` folders: https://circleci.com/docs/2.0/yarn/#caching

**Comment by snario** [comment]
#209 fixed this specific issue. Probably should look into @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll's comment above though.

**Comment by cf19drofxots** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll Do you know what the effective difference is?

The article doesn't mention how saving the yarn cache is different than saving the `node_modules` folders. I even verified that the content of the packages being saved is identical between the two (not really surprising).

So curious as to why following their recommendation is necessarily better.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
the deeper issue is that the `yarn` command should not go from a failing state to a passing state just because `node_modules` is changed...

**Comment by cf19drofxots** [comment]
It didn't go from a failing to passing state because `node_modules` was changed.

It was because the local yarn version was different from the one used in CI, producing a `yarn.lock` version of a different format. Since saving/restoring the dependencies (regardless of whether that's `~/.cache/yarn` or `node_modules`) relied on the checksum of the `yarn.lock` file, using different `yarn.lock` files resulted in the fails, not the actual cache.

**Comment by cf19drofxots** [comment]
But we're digressing, this is far from pressing. Can revisit when/if this becomes an actual issue.

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
> It didn't go from a failing to passing state because node_modules was changed.

I must be understanding it wrong, I thought the only purpose of the `restore-cache` step is to populate the `node_modules` directory. The only effect of changing the cache key on the test job, is that a different `node_modules` will be used, right?
