### ISSUE TITLE
[metamask] LocalStorage is setting "undefined" key with legacy NODE_MNEMONIC

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#2128]
![image](https://user-images.githubusercontent.com/118913/62476912-48674300-b77e-11e9-9477-4a7c7ac97ccf.png)

**Comment by cf19drofxots** [comment]
This just describes how there was a mnemonic and now there's an `EXTENDED_PRIVATE_KEY` which replaces the need for this mnemonic. Given the current state of the project, a migration path didn't seem needed.

So @joelalejandro what's the exact issue here?

**Comment by joelalejandro** [comment]
Nope, what this describes is that there's a localStorage key called `undefined`.

Either we fix the name of the key, or we stop storing the mnemonic.

**Comment by cf19drofxots** [comment]
Ah in that case, then yeah, we should stop storing the mnemonic.

**Comment by joelalejandro** [comment]
Confirmed that this is a problem with the current implementation of the CF plugin in MetaMask.
