### ISSUE TITLE
[cf-adjudicator-contracts] One of the users could submit fake challenges until maxChallengeCounter is reached

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2284]
From Decenter audit:

File name: ​MixinSetState.sol
According to current implementation of setState, in case two participants pre-agree that if the challenge counter ever reaches the maxChallengeCounter value the application should conclude with a predetermined outcome, one of the participants could possible use a contract to send all the moves from their history if they realize they are about to lose and then the contract would create fake challenges by calling the setState() method all within a single transaction until the maxChallengeCounter value is reached.
Our recommended solution would be to only allow participant accounts to send in their moves and that one user cannot call the setState function if they are already the latestSubmitter.

**Comment by rhlsthrm** [comment]
Seems wrong in terms of the understanding of the function, @snario can elaborate.

**Comment by ArjunBhuptani** [comment]
@snario what was the misunderstanding here? Could you post an explanation here so that I can refer the Decenter team to it? Thanks!

**Comment by snario** [comment]
The variable `maxChallengeCounter` does not exist. I assume this references `challengeCounter`. This value does not have a maximum except the max `uint256` value, but it is only possible to increment it one at a time.

**Comment by ArjunBhuptani** [comment]
Closing - resolved this with Decenter. Thanks @snario!
