### ISSUE TITLE
[cf-funding-protocol-contracts] An unnecessary number of transaction calls is being created

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2287]
From Decenter audit:

File name:​ MinimumViableMultisig.sol

Adding a constructor method with the possibility to add owners directly in the constructor would consequently reduce the number of required transaction calls.

**Comment by rhlsthrm** [comment]
Not really valid due to the nature of the proxy contract.

**Comment by snario** [comment]
This contract is deployed once as a singleton and the `Proxy` simply maps to it

**Comment by ArjunBhuptani** [comment]
Closing since this one looks like a WONTFIX
