### ISSUE TITLE
[cf-adjudicator-contracts] Gas usage could be reduced by 40 000 units

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2288]
From Decenter audit:

File name: ​LibStateChannel.sol (lines 32-39): ​AppChallenge struct
You can achieve a reduction of gas usage by 40 000 for each transaction that adds a new AppChallenge to storage if you were to replace:
```
struct AppChallenge { 
  ChallengeStatus status; 
  address latestSubmitter; 
  bytes32 appStateHash; 
  uint256 challengeCounter; 
  uint256 finalizesAt; 
  uint256 versionNumber;
}
```
With:
```
struct AppChallenge {
  address latestSubmitter;
  bytes32 appStateHash;
  uint128 challengeCounter;
  uint128 versionNumber; 
  uint248 finalizesAt;
  ChallengeStatus status; 
}
```

**Comment by rhlsthrm** [comment]
Closed via #2300

**Comment by ArjunBhuptani** [comment]
Missed one: `challengeCounter` should be changed to `uint128`

**Comment by ArjunBhuptani** [comment]
Fixed: https://github.com/counterfactual/monorepo/pull/2434
