### ISSUE TITLE
[cf-adjudicator-contracts] Player can create a challenge back to a wrongfully played move in order to change the outcome of the game

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2289]
From Decenter audit:

File name: ​MixinRespondToChallenge.sol
(lines 73-82): ​respondToChallenge() function
In case a user misses the chance to win and later in the game figures out which move cost him the game and could have instead been a winning one, they can create a challenge with the old state. Having returned the game back to that move, they can then apply the winning action and eventually claim victory over their opponent.
We believe it would be good to allow the second user to challenge this game result altering challenge by sending the previously recorded (non-winning) move from the first user.

**Comment by ArjunBhuptani** [comment]
@snario any updates on this?

**Comment by snario** [comment]
Not yet fixed but I agree this is an issue.

**Comment by ArjunBhuptani** [comment]
Fixed via https://github.com/counterfactual/monorepo/pull/2443
