### ISSUE TITLE
[node] Deposit confirmed not emitting anymore

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2304]
I am not seeing the deposit confirmed message at all when depositing, on either the counterparty or the initiating party. Node version is 0.2.65.

**Comment by cf19drofxots** [comment]
@rhlsthrm when you confirm if this is fixed or not via https://github.com/counterfactual/monorepo/pull/2321 ping back here

**Comment by rhlsthrm** [comment]
Just tested, it's fixed! Thanks @cf19drofxots
