### ISSUE TITLE
[contracts] No build directories in latest cf-funding-protocol-contracts package

### ISSUE THREAD

**Issue by rhlsthrm** [counterfactual/monorepo#2323]
Latest funding protocol contracts does not have build directory.

**Comment by cf19drofxots** [comment]
That's correct - it's now `expected-build-artifacts` and the node code references this new path.

Given this, can you point out what the remaining issue is?

**Comment by rhlsthrm** [comment]
In a blank project, I installed both contracts packages from NPM. The versions that installed were:
```
@counterfactual/cf-funding-protocol-contracts@0.0.8
@counterfactual/cf-adjudicator-contracts@0.0.4
```

When I inspect both packages in the node_modules directory, I see the following:

```
$ ls cf-adjudicator-contracts/                                                                                                                    
LICENSE      README.md    build        contracts    networks     package.json
$ ls cf-funding-protocol-contracts/                                                                                                               
LICENSE      README.md    contracts    networks     package.json
```

As you can see, `cf-adjudicator-contracts` contains the expected `build` directory, but `cf-funding-protocol-contracts` does not. This leads me to believe there is a specific issue with the latest publish of that package. Also, the `expected-build-artifacts` directory is present in the source code, but not in the published package on NPM.

**Comment by cf19drofxots** [comment]
@rhlsthrm can you try again with the updated versions?

**Comment by rhlsthrm** [comment]
Cool looks like that fixed the issue! Thanks @cf19drofxots
