### ISSUE TITLE
[node] Move mnemonic out of store & into memory

### ISSUE THREAD

**Issue by bohendo** [counterfactual/monorepo#2534]
Right now, the cf node needs the following to initialize: messaging service, store service, node config (aka just the store prefix?), eth provider, contract addresses, lock service, n blocks for confirmation.

My proposal: add a mnemonic to this set of init inputs (instead of passing it via the store service). This would be a breaking change.. while we're making breaking changes, we could add the eth provider url, contract addresses, and n blocks to confirm to the node config?

This way, the init params would be 1 secret (mnemonic), 3 services (store, messaging, lock), and a config object (store prefix, eth provider url, contract addresses, blocks to confirm)

Is there any reason not to include more config-type params in the NodeConfig?

If not & if this sounds reasonable then I could start on a PR for this in the near future.

**Comment by ArjunBhuptani** [comment]
This should also be bundled into the changes needed to support an external keyGen fn for per-app ephemeral keys instead of a mnemonic

**Comment by cf19drofxots** [comment]
Besides the part about updating the config struct, this issue can be closed as of the merge of https://github.com/counterfactual/monorepo/pull/2034

Comment if that's not the case, and what else is needed
