### ISSUE TITLE
Improve efficiency of CircleCI build steps

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#442]
At the moment, we run `yarn build` once here:

https://github.com/counterfactual/monorepo/blob/9bbcafe43d18943631a92b8bf07ea8d4b1b49630/.circleci/config.yml#L13

and then again for each other job:

https://github.com/counterfactual/monorepo/blob/9bbcafe43d18943631a92b8bf07ea8d4b1b49630/.circleci/config.yml#L28

https://github.com/counterfactual/monorepo/blob/9bbcafe43d18943631a92b8bf07ea8d4b1b49630/.circleci/config.yml#L40

So it runs 3 times.

This is inefficient and it would be nice to just have to run it once and re-use the output.

**Comment by mvanderh** [comment]
Each `yarn build` takes about 2min10sec. This would indeed be a valuable speedup and could knock CI time down by 4+ min.

**Comment by snario** [comment]
Solved using workspaces.
