### ISSUE TITLE
[playground] The multisig's balance should be periodically updated

### ISSUE THREAD

**Issue by joelalejandro** [counterfactual/monorepo#452]
Since the multisig can receive funds from the Playground (since #451) but also from anywhere outside the Playground, we should poll the address' balance using `web3.eth.getBalance` against the multisig's address and sync the state with [AccountTunnel.updateAccount()](https://github.com/counterfactual/monorepo/blob/master/packages/playground/src/data/account.tsx#L8).

**Comment by snario** [comment]
Need to decide what the behaviour should be here... Excess funds just behave like funds in a generic multisig.
