### ISSUE TITLE
Classes representing app instances should inherit from the same interface

### ISSUE THREAD

**Issue by mvanderh** [counterfactual/monorepo#543]
Currently, there are 3 main classes that all represent an app instance, with different fields and used for different purposes. While they can't be made the same classes functionally, they should all inherit from AppInstanceInfo or a similar interface such that they all share the same data fields. 

This will simplify these classes.

**Comment by snario** [comment]
I think we're at a reasonable minimal set now. The proposed app instance, the frontend event-emitter based representation of the app instance, and the actual saved object.
