### ISSUE TITLE
[repo] Investigate why extended key path derivation is slow

### ISSUE THREAD

**Issue by snario** [counterfactual/monorepo#778]
Naive profiling reveals that deriving paths from an extended key is slow and takes up a significant amount of time. We should investigate ways to improve this. cc @IIIIllllIIIIllllIIIIllllIIIIllllIIIIll @ricmoo

**Comment by ricmoo** [comment]
What path does the extended key represent and what path is being derived?

Node or browser? Sha2-512 is not very performant, but I’m planning on making v5 use the crypto version for node.

How slow?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
A quick sample: `fromExtendedKey("xpub6E7BR59KtqbeZg98VGEBAtgBb6MPw3xsVnF9TQQyRpFBerY4LJvotYajhT9UFEHB78Q1BCZQATNGi5A3FhJZxRMcwo3mwpJyRp6NePvEoFo").derivePath("0")` took 0.189s

**Comment by ricmoo** [comment]
Browser or node?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
node :)

**Comment by snario** [comment]
@IIIIllllIIIIllllIIIIllllIIIIllllIIIIll can you detail some ideas on improvements?

**Comment by ricmoo** [comment]
What platform are you using? Running your exact code above I get it completing in 23ms (0.023s). What platform are you on? Is it a TravisCI instance, which is highly virtualized? What is the output of `console.log(ethers.platform)`? How are you timing it?

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
So apparently this only happens under jest. Really not sure where the bug lies.

Minimum setup to reproduce: https://github.com/IIIIllllIIIIllllIIIIllllIIIIllllIIIIll/jest-ethers-bug

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
Maybe related: https://github.com/facebook/jest/issues/5163#issuecomment-355509597

**Comment by IIIIllllIIIIllllIIIIllllIIIIllllIIIIll** [comment]
Fixed by https://github.com/counterfactual/monorepo/pull/1187

@ricmoo : not sure if this is within the scope of ethers, but maybe there's a way of detecting if the key derivation function is run under a VM (https://nodejs.org/api/vm.html) and warning that it will be very slow?

**Comment by ricmoo** [comment]
Definitely out of ethers scope. :p
